server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - ${FRONTEND_ORIGIN:http://54.167.22.94}
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - Authorization
      routes:
        - id: auth-service
          uri: http://${AUTH_HOST:172.31.28.200}:8081
          predicates:
            - Path=/api/auth/**
        - id: donacion-service
          uri: http://${DONACION_HOST:172.31.28.200}:8082
          predicates:
            - Path=/api/donaciones/**
        - id: logistica-service
          uri: http://${LOGISTICA_HOST:172.31.28.200}:8083
          predicates:
            - Path=/api/logistica/**,/api/centros/**
        - id: necesidad-service
          uri: http://${NECESIDAD_HOST:172.31.28.200}:8084
          predicates:
            - Path=/api/necesidades/**
        - id: ms-usuarios
          uri: http://172.31.28.200:8085
          predicates:
            - Path=/usuarios/**
        - id: matching-service
          uri: http://${MATCHING_HOST:172.31.28.200}:8086
          predicates:
            - Path=/api/matching/**
        - id: notificaciones-service
          uri: http://${NOTIFICACIONES_HOST:172.31.28.200}:8087
          predicates:
            - Path=/api/notificaciones/**
