server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: auth-service
          uri: http://${AUTH_HOST:localhost}:8081
          predicates:
            - Path=/api/auth/**
        - id: donacion-service
          uri: http://${DONACION_HOST:localhost}:8082
          predicates:
            - Path=/api/donaciones/**
        - id: logistica-service
          uri: http://${LOGISTICA_HOST:localhost}:8083
          predicates:
            - Path=/api/logistica/**,/api/centros/**
        - id: necesidad-service
          uri: http://${NECESIDAD_HOST:localhost}:8084
          predicates:
            - Path=/api/necesidades/**
