spring.application.name=ms-usuarios
server.port=8085

# Conexión real a Azure PostgreSQL
spring.datasource.url=jdbc:postgresql://donaton-db-server.postgres.database.azure.com:5432/postgres?sslmode=require
spring.datasource.username=donatonadmin
spring.datasource.password=ManboWeko22!
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.com.donaton=DEBUG
